### ISSUE TITLE
onChange event is not getting called when content is added via plugin like mathtype or wiris

### ISSUE THREAD

**Issue by mKadiyan** [ckeditor/ckeditor4#3817]
Bug

Add any content to editor from plugin.(mathtype, easy image or wiris), content is displayed in editor but on change event is not getting called. although event get called when you directly type in editor.

**Comment by jacekbogdanski** [comment]
I cannot reproduce the issue with the Easy Image plugin. Could you provide a minimal working demo with the issue?

MathType seems to not fire `change` event after insertion indeed. It's only fired when opening the MathType panel.

**Comment by henok-tesfaye** [comment]
This is a bug, `onChange` is not called when adding a formula using mathtype icon.

**Comment by f1ames** [comment]
@jacekbogdanski if it only concerns MathType plugin we should forward it to Wiris team, unless it is something which should be fixed directly in CKEditor 4 core :thinking:

**Comment by henok-tesfaye** [comment]
@f1ames I tried it with CKEditor5 and It is working.

**Comment by jacekbogdanski** [comment]
Looks like MathType upstream TBO as we explicitly tell whenever undo manager should create an undo step. E.g. see colorbutton plugin - https://github.com/ckeditor/ckeditor4/blob/040782c393afa8819e008b1b1837b2cce0096c19/plugins/colorbutton/plugin.js#L111-L129

the snapshot is explicitly saved for success path. It looks similar with other plugins.

**Comment by carlawiris** [comment]
The bug is fixed in version 7.20.0 and above. Soon the version of the plugin in the page https://ckeditor.com/mathtype/demo/#ckeditor4 will be updated so you can try the demo with the 'change' event working as expected.

**Comment by henok-tesfaye** [comment]
Thank you @carlawiris .

```
export const addWirisPlugin = CKEDITOR => {
  CKEDITOR.plugins.addExternal('ckeditor_wiris', 'https://www.wiris.net/demo/plugins/ckeditor/', 'plugin.js')
}
```

I integrated mathtype plugin in my CKEditor using wiris demo. How can I get the fix then?

**Comment by f1ames** [comment]
@carlawiris I see that the suggested external integration URL (which is https://www.wiris.net/demo/plugins/ckeditor/plugin.js and described in https://docs.wiris.com/en/mathtype/mathtype_web/integrations/html/ckeditor#external_integration) still has older version (`7.14`). Are there any plans to update it or you need different approach to use newer version?

**Comment by carlawiris** [comment]
Thank you for the information. The version of the plugin on https://www.wiris.net/demo/plugins/ckeditor/plugin.js is outdated, we are working on updating it. 

In the meantime we recommend that you follow the instructions and download the plugin from the npm site where the information is the latest. (https://www.npmjs.com/package/@wiris/mathtype-ckeditor4)

**Comment by f1ames** [comment]
Thanks for clarification @carlawiris, I'm closing this as it is solved already (starting from `7.20.0` version as you mentioned) - cc @mKadiyan .

For future reference, the recommended way to add MathType plugin to CKEditor 4 is via NPM.

**Comment by henok-tesfaye** [comment]
Hi @f1ames

I added Mathtype plugin to CKEditor4 via NPM(https://github.com/ckeditor/ckeditor4-react/issues/117#issuecomment-687100372) and checked that I'm still getting this issue in version `7.22.0`, CKEditor onChange is not called when you edit or add math using mathtype without editing other content(since change on the CKEditor will trigger the event).

**Comment by henok-tesfaye** [comment]
@f1ames any update on this 🤔? Thanks!

**Comment by jvanwyk1** [comment]
the event is being fired now, when inserting mathtype formula,
but when calling this.getData() inside change event handler, it is empty.

so change event gets fired now, but no data is being passed, 
or the event gets raised before data gets passed to editor.

**Comment by f1ames** [comment]
Hi @henok-tesfaye,

it seems [our demo](https://ckeditor.com/mathtype/demo/#ckeditor4) still uses older `7.16.x` version where this issue is present. However, you can check [documentation example](https://ckeditor.com/docs/ckeditor4/latest/examples/mathtype.html) where `7.22.0` is used and it works as expected:

![](https://user-images.githubusercontent.com/1061942/93179970-ba0e1080-f736-11ea-82b5-216edc9e8208.gif)

**Comment by f1ames** [comment]
@jvanwyk1 since this is slightly different issue could you report it as a separate one?

**Comment by henok-tesfaye** [comment]
Thank you @f1ames `onChange` is now triggered. 

I'm also facing similar issue that @jvanwyk1 pointed out.

@jvanwyk1 can you please create a new ticket?
